### ISSUE TITLE
Maven and IntelliJ build failures

### ISSUE THREAD

**Issue by JapuDCret** [devlauer/plantuml-generator#18]
For me several tests fail in IntelliJ and with Maven.

It seems that the usage of a custom classloader was not done correctly and then in other tests it was copied over.

Full Maven output
```bash
user@pc MINGW64 /c/git/plantuml-generator/plantuml-generator-util (master)
$ mvn clean package
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] --------------< de.elnarion.util:plantuml-generator-util >--------------
[INFO] Building plantuml-generator-util 1.2.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ plantuml-generator-util ---
[INFO] Deleting C:\git\plantuml-generator\plantuml-generator-util\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ plantuml-generator-util ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\git\plantuml-generator\plantuml-generator-util\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ plantuml-generator-util ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 15 source files to C:\git\plantuml-generator\plantuml-generator-util\target\classes
[INFO] /C:/git/plantuml-generator/plantuml-generator-util/src/main/java/de/elnarion/util/plantuml/generator/PlantUMLClassDiagramGenerator.java: C:\git\plantuml-generator\plantuml-generator-util\src\main\java\de\elnarion\util\plantuml\generator\PlantUMLClassDiagramGenerator.java uses or overrides a deprecated API.
[INFO] /C:/git/plantuml-generator/plantuml-generator-util/src/main/java/de/elnarion/util/plantuml/generator/PlantUMLClassDiagramGenerator.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ plantuml-generator-util ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 28 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ plantuml-generator-util ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 49 source files to C:\git\plantuml-generator\plantuml-generator-util\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ plantuml-generator-util ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest
@startuml

class de.elnarion.test.domain.t0022.TestPrivateFinalObject {
        {field} -PRIVATE_CONSTANT : String
        {field} -PRIVATE_CONSTANT_INT : int
        {field} #PROTECTED_CONSTANT : String
        {field} #PROTECTED_CONSTANT_INT : int
        {field} +PUBLIC_CONSTANT : String
        {field} +PUBLIC_CONSTANT_INT : int
        {field} -nonconstant : String
        {field} -nonconstant2 : int
        {field} #nonconstant2Protected : int
        {field} +nonconstant2Public : int
        {field} #nonconstantProtected : String
        {field} +nonconstantPublic : String
        {method} +doSomething () : void
}






@enduml
@startuml

class de.elnarion.test.domain.t0021.Family <<Entity>>  {
        {field} +description : String
        {field} +@Id id : int
}


class de.elnarion.test.domain.t0021.Job <<Entity>>  {
        {field} +@Id id : int
        {field} +jobDescr : String
        {field} +salery : double
}


class de.elnarion.test.domain.t0021.Person <<Entity>>  {
        {field} +firstName : String
        {field} +@Id id : String
        {field} +lastName : String
        {field} +@Transient nonsenseField : String
}


class de.elnarion.test.domain.t0021.Todo <<Entity>>  <<Table (schema=SCHEMA,name=TABLENAME)>>  {
        {field} +@Column("DESCR") description : String
        {field} +@Column("IDX") @Id id : Long
}


enum de.elnarion.test.domain.t0021.TodoStateEnum {
        {field} +CLOSED
        {field} +IN_PROGRESS
        {field} +OPEN
}




de.elnarion.test.domain.t0021.Family "1" o-- "0..*"  de.elnarion.test.domain.t0021.Person :  @OneToMany\nmembers
de.elnarion.test.domain.t0021.Person "1" o-- "0..*"  de.elnarion.test.domain.t0021.Job :  @OneToMany\njobList
de.elnarion.test.domain.t0021.Person -->  de.elnarion.test.domain.t0021.Family :  @ManyToOne\nfamily
de.elnarion.test.domain.t0021.Todo -->  de.elnarion.test.domain.t0021.TodoStateEnum :  @Column("STATE")\nstate


@enduml
[ERROR] Tests run: 22, Failures: 8, Errors: 0, Skipped: 0, Time elapsed: 1.158 s <<< FAILURE! - in de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest
[ERROR] test0019IgnoreClassifierFields(de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest)  Time elapsed: 0.119 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<@startuml[abstractclassde.elnarion.test.domain.t0019.Testclass{{field}+test10:String{field}-test2:String{field}-test3:String{field}#test4:String{field}#test6:String{field}#test7:String{field}+test9:String}]@enduml> but was:<@startuml[]@enduml>
        at de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest.test0019IgnoreClassifierFields(PlantUMLClassDiagramGeneratorTest.java:493)

[ERROR] test0018BlacklistFields(de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest)  Time elapsed: 0.014 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<@startuml[classde.elnarion.test.domain.t0018.Testclass1{{field}+testfield:long{method}+doSomething():void}classde.elnarion.test.domain.t0018.Testclass2{{method}#doSomething():void}de.elnarion.test.domain.t0018.Testclass1-->de.elnarion.test.domain.t0018.Testclass2:testfield2]@enduml> but was:<@startuml[]@enduml>
        at de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest.test0018BlacklistFields(PlantUMLClassDiagramGeneratorTest.java:471)

[ERROR] test0015RemoveMethods(de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest)  Time elapsed: 0.014 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<@startuml[classde.elnarion.test.domain.t0015.Testclass1{{field}+testfield:long}classde.elnarion.test.domain.t0015.Testclass2{}de.elnarion.test.domain.t0015.Testclass1-->de.elnarion.test.domain.t0015.Testclass2:testfield2]@enduml> but was:<@startuml[]@enduml>
        at de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest.test0015RemoveMethods(PlantUMLClassDiagramGeneratorTest.java:404)

[ERROR] test0014MaxVisibilityMethods(de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest)  Time elapsed: 0.015 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<@startuml[classde.elnarion.test.domain.t0014.Testclass{{method}+doSomething4():void}]@enduml> but was:<@startuml[]@enduml>
        at de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest.test0014MaxVisibilityMethods(PlantUMLClassDiagramGeneratorTest.java:354)

[ERROR] test0020IgnoreClassifierMethods(de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest)  Time elapsed: 0.016 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<@startuml[abstractclassde.elnarion.test.domain.t0020.Testclass{{method}{abstract}+doSomething():void}interfacede.elnarion.test.domain.t0020.Testinterface{{method}{abstract}+doSomething():void{method}{abstract}+doSomething2():void{method}+doSomething3():void}]@enduml> but was:<@startuml[]@enduml>
        at de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest.test0020IgnoreClassifierMethods(PlantUMLClassDiagramGeneratorTest.java:515)

[ERROR] test0017BlacklistMethods(de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest)  Time elapsed: 0.015 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<@startuml[classde.elnarion.test.domain.t0017.Testclass1{{field}+testfield:long}classde.elnarion.test.domain.t0017.Testclass2{{method}#doSomething():void}de.elnarion.test.domain.t0017.Testclass1-->de.elnarion.test.domain.t0017.Testclass2:testfield2]@enduml> but was:<@startuml[]@enduml>
        at de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest.test0017BlacklistMethods(PlantUMLClassDiagramGeneratorTest.java:449)

[ERROR] test0016RemoveFields(de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest)  Time elapsed: 0.013 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<@startuml[classde.elnarion.test.domain.t0016.Testclass1{{method}+doSomething():void}classde.elnarion.test.domain.t0016.Testclass2{{method}#doSomething():void}de.elnarion.test.domain.t0016.Testclass1-->de.elnarion.test.domain.t0016.Testclass2:testfield2]@enduml> but was:<@startuml[]@enduml>
        at de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest.test0016RemoveFields(PlantUMLClassDiagramGeneratorTest.java:427)

[ERROR] test0013MaxVisibilityFields(de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest)  Time elapsed: 0.015 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<@startuml[classde.elnarion.test.domain.t0013.Testclass{{field}+test4:long{field}+test5:long}]@enduml> but was:<@startuml[]@enduml>
        at de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGeneratorTest.test0013MaxVisibilityFields(PlantUMLClassDiagramGeneratorTest.java:305)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   PlantUMLClassDiagramGeneratorTest.test0013MaxVisibilityFields:305 expected:<@startuml[classde.elnarion.test.domain.t0013.Testclass{{field}+test4:long{field}+test5:long}]@enduml> but was:<@startuml[]@enduml>
[ERROR]   PlantUMLClassDiagramGeneratorTest.test0014MaxVisibilityMethods:354 expected:<@startuml[classde.elnarion.test.domain.t0014.Testclass{{method}+doSomething4():void}]@enduml> but was:<@startuml[]@enduml>
[ERROR]   PlantUMLClassDiagramGeneratorTest.test0015RemoveMethods:404 expected:<@startuml[classde.elnarion.test.domain.t0015.Testclass1{{field}+testfield:long}classde.elnarion.test.domain.t0015.Testclass2{}de.elnarion.test.domain.t0015.Testclass1-->de.elnarion.test.domain.t0015.Testclass2:testfield2]@enduml> but was:<@startuml[]@enduml>
[ERROR]   PlantUMLClassDiagramGeneratorTest.test0016RemoveFields:427 expected:<@startuml[classde.elnarion.test.domain.t0016.Testclass1{{method}+doSomething():void}classde.elnarion.test.domain.t0016.Testclass2{{method}#doSomething():void}de.elnarion.test.domain.t0016.Testclass1-->de.elnarion.test.domain.t0016.Testclass2:testfield2]@enduml> but was:<@startuml[]@enduml>
[ERROR]   PlantUMLClassDiagramGeneratorTest.test0017BlacklistMethods:449 expected:<@startuml[classde.elnarion.test.domain.t0017.Testclass1{{field}+testfield:long}classde.elnarion.test.domain.t0017.Testclass2{{method}#doSomething():void}de.elnarion.test.domain.t0017.Testclass1-->de.elnarion.test.domain.t0017.Testclass2:testfield2]@enduml> but was:<@startuml[]@enduml>
[ERROR]   PlantUMLClassDiagramGeneratorTest.test0018BlacklistFields:471 expected:<@startuml[classde.elnarion.test.domain.t0018.Testclass1{{field}+testfield:long{method}+doSomething():void}classde.elnarion.test.domain.t0018.Testclass2{{method}#doSomething():void}de.elnarion.test.domain.t0018.Testclass1-->de.elnarion.test.domain.t0018.Testclass2:testfield2]@enduml> but was:<@startuml[]@enduml>
[ERROR]   PlantUMLClassDiagramGeneratorTest.test0019IgnoreClassifierFields:493 expected:<@startuml[abstractclassde.elnarion.test.domain.t0019.Testclass{{field}+test10:String{field}-test2:String{field}-test3:String{field}#test4:String{field}#test6:String{field}#test7:String{field}+test9:String}]@enduml> but was:<@startuml[]@enduml>
[ERROR]   PlantUMLClassDiagramGeneratorTest.test0020IgnoreClassifierMethods:515 expected:<@startuml[abstractclassde.elnarion.test.domain.t0020.Testclass{{method}{abstract}+doSomething():void}interfacede.elnarion.test.domain.t0020.Testinterface{{method}{abstract}+doSomething():void{method}{abstract}+doSomething2():void{method}+doSomething3():void}]@enduml> but was:<@startuml[]@enduml>
[INFO]
[ERROR] Tests run: 22, Failures: 8, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.595 s
[INFO] Finished at: 2021-12-09T12:19:49+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project plantuml-generator-util: There are test failures.
[ERROR]
[ERROR] Please refer to C:\git\plantuml-generator\plantuml-generator-util\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

user@pc MINGW64 /c/git/plantuml-generator/plantuml-generator-util (master)
```

**Comment by JapuDCret** [comment]
@devlauer bump
